dist: focal
sudo: required
language: cpp
compiler: gcc
os: linux

addons:
    apt:
        packages:
        - cmake
        - g++
        - libgl1-mesa-dev
        - libglu1-mesa-dev

matrix:
    include:
    - name: "Debug build"
      env: BUILD_TYPE=Debug
    - name: "Release build"
      env: BUILD_TYPE=RelWithDebInfo

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOPTICK_ENABLED=OFF
    - cmake --build .
